-- Eliminar restricciones de clave externa
ALTER TABLE User_Roles DROP CONSTRAINT fk_User_Roles_UserID; --
ALTER TABLE User_Roles DROP CONSTRAINT fk_User_Roles_RoleID;
ALTER TABLE Products DROP CONSTRAINT fk_Products_CategoryID;
ALTER TABLE Product_Reviews DROP CONSTRAINT fk_Product_Reviews_UserID; --
ALTER TABLE Product_Reviews DROP CONSTRAINT fk_Product_Reviews_ProductID;
ALTER TABLE Orders DROP CONSTRAINT fk_Orders_UserID; --
ALTER TABLE Orders DROP CONSTRAINT fk_Orders_PaymentMethodID;
ALTER TABLE Orders DROP CONSTRAINT fk_Orders_ShippingMethodID;
ALTER TABLE Order_Items DROP CONSTRAINT fk_Order_Items_OrderID;
ALTER TABLE Order_Items DROP CONSTRAINT fk_Order_Items_ProductID;
ALTER TABLE Cart DROP CONSTRAINT fk_Cart_UserID; --
ALTER TABLE Cart_Items DROP CONSTRAINT fk_Cart_Items_CartID;
ALTER TABLE Cart_Items DROP CONSTRAINT fk_Cart_Items_ProductID; --
ALTER TABLE Applied_Promotions DROP CONSTRAINT fk_Applied_Promotions_OrderID;
ALTER TABLE Applied_Promotions DROP CONSTRAINT fk_Applied_Promotions_PromotionID;
ALTER TABLE Notifications DROP CONSTRAINT fk_Notifications_UserID; --
ALTER TABLE Rewards DROP CONSTRAINT fk_Rewards_UserID;

-- Eliminar tablas existentes si existen
DROP TABLE Users CASCADE CONSTRAINTS;
DROP TABLE Roles CASCADE CONSTRAINTS;
DROP TABLE User_Roles CASCADE CONSTRAINTS;
DROP TABLE Products CASCADE CONSTRAINTS;
DROP TABLE Categories CASCADE CONSTRAINTS;
DROP TABLE Product_Reviews CASCADE CONSTRAINTS;
DROP TABLE Orders CASCADE CONSTRAINTS;
DROP TABLE Order_Items CASCADE CONSTRAINTS;
DROP TABLE Payment_Methods CASCADE CONSTRAINTS;
DROP TABLE Shipping_Methods CASCADE CONSTRAINTS;
DROP TABLE Cart CASCADE CONSTRAINTS;
DROP TABLE Cart_Items CASCADE CONSTRAINTS;
DROP TABLE Promotions CASCADE CONSTRAINTS;
DROP TABLE Applied_Promotions CASCADE CONSTRAINTS;
DROP TABLE Notifications CASCADE CONSTRAINTS;
DROP TABLE Rewards CASCADE CONSTRAINTS;

-- Crear tabla Users con una columna de identidad
CREATE TABLE Users (
  UserID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  Username NVARCHAR2(50) UNIQUE NOT NULL,
  Password NVARCHAR2(255) NOT NULL,
  Email NVARCHAR2(100) UNIQUE NOT NULL,
  FirstName NVARCHAR2(50),
  LastName NVARCHAR2(50),
  Address NVARCHAR2(255),
  Phone NVARCHAR2(15),
  Last_Login DATE,
  Require_Change_Password NUMBER(1) DEFAULT 1,
  Enabled NUMBER(1) DEFAULT 1,
  Disabled_Date DATE
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Roles con una columna de identidad
CREATE TABLE Roles (
  RoleID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  RoleName NVARCHAR2(50) NOT NULL
);

-- Crear tabla User_Roles con una columna de identidad
CREATE TABLE User_Roles (
  User_RoleID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  UserID NUMBER NOT NULL,
  RoleID NUMBER NOT NULL
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Products con una columna de identidad
CREATE TABLE Products (
  ProductID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  Name NVARCHAR2(100) NOT NULL,
  Description NVARCHAR2(255),
  Price NUMBER(10, 2) NOT NULL,
  StockQuantity NUMBER NOT NULL,
  CategoryID NUMBER NOT NULL
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Categories con una columna de identidad
CREATE TABLE Categories (
  CategoryID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  CategoryName NVARCHAR2(50) NOT NULL,
  Enabled NUMBER(1) DEFAULT 1,
  DISABLED_DATE TIMESTAMP (6)
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Product_Reviews con una columna de identidad
CREATE TABLE Product_Reviews (
  ReviewID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  UserID NUMBER,
  ProductID NUMBER,
  Rating NUMBER(3, 1) NOT NULL,
  Comments NVARCHAR2(255),
  Timestamp TIMESTAMP
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Orders con una columna de identidad
CREATE TABLE Orders (
  OrderID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  UserID NUMBER,
  OrderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  TotalAmount NUMBER(10, 2),
  PaymentMethodID NUMBER,
  ShippingMethodID NUMBER
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Order_Items con una columna de identidad
CREATE TABLE Order_Items (
  OrderItemID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  OrderID NUMBER,
  ProductID NUMBER,
  Quantity NUMBER NOT NULL,
  Subtotal NUMBER(10, 2)
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Payment_Methods con una columna de identidad
CREATE TABLE Payment_Methods (
  PaymentMethodID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  PaymentMethodName NVARCHAR2(50) NOT NULL,
  Enabled NUMBER(1) DEFAULT 1
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Shipping_Methods con una columna de identidad
CREATE TABLE Shipping_Methods (
  ShippingMethodID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  ShippingMethodName NVARCHAR2(50) NOT NULL,
  ShippingCost NUMBER(10, 2)
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Cart con una columna de identidad
CREATE TABLE Cart (
  CartID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  UserID NUMBER
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Cart_Items con una columna de identidad
CREATE TABLE Cart_Items (
  CartItemID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  CartID NUMBER,
  ProductID NUMBER,
  Quantity NUMBER NOT NULL
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Promotions con una columna de identidad
CREATE TABLE Promotions (
  PromotionID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  PromotionName NVARCHAR2(100) NOT NULL,
  DiscountAmount NUMBER(10, 2) NOT NULL,
  StartDate DATE,
  EndDate DATE
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Applied_Promotions con una columna de identidad
CREATE TABLE Applied_Promotions (
  AppliedPromotionID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  OrderID NUMBER,
  PromotionID NUMBER
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Notifications con una columna de identidad
CREATE TABLE Notifications (
  NotificationID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  UserID NUMBER,
  Message NVARCHAR2(255),
  Timestamp TIMESTAMP
) TABLESPACE CravyPizzaHuB;

-- Crear tabla Rewards con una columna de identidad
CREATE TABLE Rewards (
  RewardID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  UserID NUMBER,
  Points NUMBER NOT NULL
) TABLESPACE CravyPizzaHuB;

-- Agregar restricciones de clave externa
ALTER TABLE User_Roles ADD CONSTRAINT fk_User_Roles_UserID FOREIGN KEY (UserID) REFERENCES Users(UserID);
ALTER TABLE User_Roles ADD CONSTRAINT fk_User_Roles_RoleID FOREIGN KEY (RoleID) REFERENCES Roles(RoleID);
ALTER TABLE Products ADD CONSTRAINT fk_Products_CategoryID FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID);
ALTER TABLE Product_Reviews ADD CONSTRAINT fk_Product_Reviews_UserID FOREIGN KEY (UserID) REFERENCES Users(UserID);
ALTER TABLE Product_Reviews ADD CONSTRAINT fk_Product_Reviews_ProductID FOREIGN KEY (ProductID) REFERENCES Products(ProductID);
ALTER TABLE Orders ADD CONSTRAINT fk_Orders_UserID FOREIGN KEY (UserID) REFERENCES Users(UserID);
ALTER TABLE Orders ADD CONSTRAINT fk_Orders_PaymentMethodID FOREIGN KEY (PaymentMethodID) REFERENCES Payment_Methods(PaymentMethodID);
ALTER TABLE Orders ADD CONSTRAINT fk_Orders_ShippingMethodID FOREIGN KEY (ShippingMethodID) REFERENCES Shipping_Methods(ShippingMethodID);
ALTER TABLE Order_Items ADD CONSTRAINT fk_Order_Items_OrderID FOREIGN KEY (OrderID) REFERENCES Orders(OrderID);
ALTER TABLE Order_Items ADD CONSTRAINT fk_Order_Items_ProductID FOREIGN KEY (ProductID) REFERENCES Products(ProductID);
ALTER TABLE Cart ADD CONSTRAINT fk_Cart_UserID FOREIGN KEY (UserID) REFERENCES Users(UserID);
ALTER TABLE Cart_Items ADD CONSTRAINT fk_Cart_Items_CartID FOREIGN KEY (CartID) REFERENCES Cart(CartID);
ALTER TABLE Cart_Items ADD CONSTRAINT fk_Cart_Items_ProductID FOREIGN KEY (ProductID) REFERENCES Products(ProductID);
ALTER TABLE Applied_Promotions ADD CONSTRAINT fk_Applied_Promotions_OrderID FOREIGN KEY (OrderID) REFERENCES Orders(OrderID);
ALTER TABLE Applied_Promotions ADD CONSTRAINT fk_Applied_Promotions_PromotionID FOREIGN KEY (PromotionID) REFERENCES Promotions(PromotionID);
ALTER TABLE Notifications ADD CONSTRAINT fk_Notifications_UserID FOREIGN KEY (UserID) REFERENCES Users(UserID);
ALTER TABLE Rewards ADD CONSTRAINT fk_Rewards_UserID FOREIGN KEY (UserID) REFERENCES Users(UserID);
